---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: config-demo-datamesh-secret
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: config-demo-datamesh-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.datameshsecret.key }}
